# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbExcelSheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheets_name', models.CharField(max_length=200)),
                ('imported_sheet', models.FileField(upload_to='files/prob_excel_sheets')),
            ],
        ),
    ]
