# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyanalysis',
            name='up_patients',
            field=models.IntegerField(),
        ),
    ]
