# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcmain', '0002_auto_20170223_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyanalysis',
            name='treatment_name',
            field=models.CharField(default='Treatment_A', max_length=200),
            preserve_default=False,
        ),
    ]
